name: Main Workflow

on:
  push:
    branches:
      - master
      - feature/*
      - feature-*/** 

  pull_request:
    types: [opened, synchronize, reopened] # Trigger when PR is opened, updated, or reopened
    branches:
      - feature/*
      - feature-*/**

jobs:

  test-application:
    uses: ./.github/workflows/test-application.yml
    with:
      MAVEN_OPTS: "-Xmx1024m"



  build-and-push:
    if: github.ref == 'refs/heads/master'
    uses: ./.github/workflows/build-image.yml
    with:
      DOCKERFILE_PATH: "./Dockerfile" 
      CONTEXT_PATH: "./"             
    secrets:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      ROLE_NAME: ${{ secrets.ROLE_NAME }}
      ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
