name: Main Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
        - feature/*

jobs:
  build_and_push:
    uses: ./.github/workflows/templates/build-and-push-ecr.yml
    with:
      DOCKERFILE_PATH: "./Dockerfile"
      CONTEXT_PATH: "./app"
      ECR_REPOSITORY: "my-ecr-repo"
    secrets:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      ROLE_NAME: ${{ secrets.ROLE_NAME }}
      APP_NAME: "my-app"
