name: Main Workflow

on:
  push:
    branches:
      - master
      - feature/*
      - feature-*
      - feature-*/**

  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - feature/*
      - feature-*
      - feature-*/**

  workflow_dispatch:
  

jobs:
  # Build and Push Job
  build-and-push:
    uses: madilshahzad/Build-Deploy/.github/workflows/build-and-push-docker.yml@main
    with:
      DOCKERFILE_PATH: "./Dockerfile" # Path to your Dockerfile
      CONTEXT_PATH: "./"             # Build context
      APP_NAME: "java-web-app"       # Application name
    secrets:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      ROLE_NAME: ${{ secrets.ROLE_NAME }}
      ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
