name: Main Workflow

on:
  # Trigger for pushes to the main branch
  push:
    branches:
      - main

  # Trigger for pull requests to feature branches
  pull_request:
    branches:
      - feature/*

  # Allow manual workflow runs
  workflow_dispatch:

jobs:

  test-application:
    uses: ./.github/workflows/test-application.yml
    with:
      MAVEN_OPTS: "-Xmx1024m"



  build-and-push:
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/build-image.yml
    with:
      DOCKERFILE_PATH: "./Dockerfile" 
      CONTEXT_PATH: "./"             
    secrets:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      ROLE_NAME: ${{ secrets.ROLE_NAME }}
      ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
