name: Main Workflow

on:
  push:
    branches:
      - master
      - feature/*
      - feature-*
      - feature-*/**

  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - feature/*
      - feature-*
      - feature-*/**

  workflow_dispatch:
    inputs:
      target_service:
        description: "Service to target"
        required: true
        default: "default-service"
      target_version:
        description: "Version to target"
        required: true
        default: "1.0.0"

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:

      - name: Build and Push Image
        run: |
          curl -H "Authorization: token ${{secrets.PAT}}" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/madilshahzad/Build-Deploy/actions/workflows/build-deploy.yml/dispatches \
              -d '{
                "ref": "main",
                "inputs": {
                  "DOCKERFILE_PATH": "./Dockerfile",
                  "CONTEXT_PATH": "./",
                  "APP_NAME": "java-web-app"
                }
              }'

