name: Main Workflow

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - feature/*

  workflow_dispatch: 

jobs:
  build_and_push:
    uses: ./.github/workflows/build-and-push-ecr.yml
    with:
      DOCKERFILE_PATH: "./Dockerfile" # Assumes Dockerfile is in the root
      CONTEXT_PATH: "./"             # Root context
    secrets:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      ROLE_NAME: ${{ secrets.ROLE_NAME }}
      ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
