name: Terraform Security Scan

on:
  workflow_call: {}
  pull_request:
    paths:
      - '**/*.tf'
  workflow_dispatch: # Allow manual trigger for tfsec

permissions:
  contents: read

jobs:
  tfsec-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install tfsec
        run: |
          curl -Lo tfsec https://github.com/aquasecurity/tfsec/releases/latest/download/tfsec-linux-amd64
          chmod +x tfsec
          sudo mv tfsec /usr/local/bin/

      - name: Run tfsec Security Scan
        run: tfsec .
